/** @type {import('jest').Config} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/*.test.ts', '**/*.integration.test.ts'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.test.ts',
    '!src/**/*.integration.test.ts',
    '!src/server.ts',
    '!src/app.ts',
    '!src/config/database.ts',
    '!src/jobs/**',
    '!src/websocket/**',
    '!src/services/mailService.ts',
    '!src/swagger/openapi.ts',
    '!src/prisma.ts',
    '!src/routes/index.ts',
    '!src/middleware/uploadAvatar.ts',
    '!src/middleware/uploadListingImage.ts',
    '!src/middleware/uploadMessageImage.ts',
    '!src/emails/templates.ts',
    '!src/modules/admin/adminController.ts',
    '!src/modules/auth/authController.ts',
    '!src/modules/auth/authRepository.ts',
    '!src/modules/conversations/conversationsController.ts',
    '!src/modules/conversations/conversationsRepository.ts',
    '!src/modules/disputes/**',
    '!src/modules/listings/listingsController.ts',
    '!src/modules/listings/listingsRepository.ts',
    '!src/modules/messages/**',
    '!src/modules/orders/ordersController.ts',
    '!src/modules/orders/ordersRepository.ts',
    '!src/modules/payments/**',
    '!src/modules/reviews/reviewsController.ts',
    '!src/modules/stripe/stripeController.ts',
    '!src/modules/users/**',
    '!src/modules/webhooks/webhooksStripeController.ts',
    '!src/modules/sitemap/**',
    '!src/modules/reviews/reviewsRoutes.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'text-summary', 'html', 'lcov'],
  setupFiles: ['<rootDir>/jest.setup.js'],
  testTimeout: 15000,
};
